# Auto-generated by relictrek-autoblog — run this if git push did not complete automatically
Set-Location $PSScriptRoot

Remove-Item -Force ".git\index.lock" -ErrorAction SilentlyContinue
Remove-Item -Force ".git\HEAD.lock"  -ErrorAction SilentlyContinue

git add .
git commit -m "auto-blog: 2026-06-03 [windrose] conquistador-armor"
git push

Write-Host "`nDone. Press Enter to close." -ForegroundColor Green
Read-Host
